kind: DeploymentConfig
apiVersion: v1
metadata:
  labels:
    app: singlecontainer
  name: singlecontainer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: singlecontainer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: singlecontainer
    spec:
      containers:
      - image: docker.io/krishnamanchikalapudi/springrestbootdocker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 60